name: Build

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.15' 
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=app-${{ matrix.os }} index.py

      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: app/dist/app-${{ matrix.os }}*
          if-no-files-found: error
